kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          name: master-node
  - role: worker
    labels:
      node-role.kubernetes.io/worker: ""
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: worker-node-1
  - role: worker
    labels:
      node-role.kubernetes.io/infra: ""
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: infra-node-1
          taints:
            - key: "node-role.kubernetes.io/infra"
              value: "reserved"
              effect: "NoSchedule"
    # Port 30080 exposed to Windows host
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP