kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  
  - role: worker
    labels:
      tier: "worker"
      
  - role: worker
    labels:
      tier: "infra"
    # Taints must be passed through kubeadm configurations
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          taints:
            - key: "infra-node"
              value: "reserved"
              effect: "NoSchedule"

#after creating the cluster, you can label and taint the nodes using kubectl commands.
# # Add the worker role label to the first worker
# kubectl label node rkd01-worker node-role.kubernetes.io/worker=""

# # Add the infra role label to the second worker
# kubectl label node rkd01-worker2 node-role.kubernetes.io/infra=""

# # 1. View all raw taints on rkd01-worker2 without findstr truncation
# kubectl get node rkd01-worker2 -o jsonpath='{.spec.taints}'

# # 2. Remove all custom taints from rkd01-worker2
# kubectl taint nodes rkd01-worker2 node-role.kubernetes.io/infra- infra-node-

# # 3. Apply a single, standard taint
# kubectl taint nodes rkd01-worker2 node-role.kubernetes.io/infra=reserved:NoSchedule --overwrite