apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-app
  namespace: app-portfolio
  labels:
    app: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      # Pinned to the general worker node
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
        - name: portfolio
          image: personal-portfolio:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: app-portfolio
spec:
  type: NodePort
  selector:
    app: portfolio
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30085 # Exposes port 30085 mapped in your Kind cluster config